# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20170929_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customer_identifier',
            field=models.CharField(default='unknown', max_length=32),
            preserve_default=False,
        ),
    ]
